# Generated by Django 5.2.3 on 2025-06-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailings", "0001_initial"),
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="message.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
